apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: proyecto2026
type: Opaque
stringData:
  APP_NAME: "ServiciosPro"
  APP_ENV: "production"
  APP_KEY: ""
  APP_DEBUG: "false"
  APP_URL: "https://api.agendaonline.cloud-ip.cc"

  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "servicios_pro"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "null"

  QUEUE_CONNECTION: "redis"
  CACHE_STORE: "redis"
  SESSION_DRIVER: "database"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "yoelleyes2013@gmail.com"
  MAIL_PASSWORD: "bdvz hvna choi hbyf"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "yoelleyes2013@gmail.com"
  MAIL_FROM_NAME: "AgendaOnline"

  SANCTUM_STATEFUL_DOMAINS: "app.agendaonline.cloud-ip.cc"
  FRONTEND_URL: "https://app.agendaonline.cloud-ip.cc"
  SANCTUM_TOKEN_EXPIRATION: "10080"

  BROADCAST_DRIVER: "reverb"
  REVERB_APP_ID: "1"
  REVERB_APP_KEY: "servipro-reverb-key"
  REVERB_APP_SECRET: "servipro-reverb-secret-2026"
  REVERB_HOST: "reverb"
  REVERB_PORT: "8080"
  REVERB_SCHEME: "http"
  RUN_MIGRATIONS: "false"

  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_REDIRECT_URI: "https://api.agendaonline.cloud-ip.cc/api/auth/google/callback"

  NOTIF_SERVICE_URL: "http://notificaciones:8002"
  NOTIF_SERVICE_TOKEN: "dev-token-local"

  PAYPAL_CLIENT_ID: "AVp0GjORfuI3WCSagsDIJOSeSVN6vRaAoIPVNgV81WDhCfGuDDdNpvsLErD3B2QcZ4RFg5FsG4cv3OtM"
  PAYPAL_SECRET: "EBT861N51oybFlavu70RA3ujp2-C4taz56xgkVMBSn8SD2hLsiGJf4p8_NST0KXXVWlFIFgXbx7boC15"
  PAYPAL_MODE: "sandbox"

  LIVEKIT_URL: "wss://servipro-fztgxuz6.livekit.cloud"
  LIVEKIT_API_KEY: "APIRX9NnvAfiDUL"
  LIVEKIT_API_SECRET: "VXbcPaXi1Re0PeuefCeY4OHPB7hc2bcZRMvuSmIJCyfE"

  ATLAS_MONGODB_URI: ""
  ATLAS_LOGS_ENABLED: "false"
