apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: proyecto2026
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
