apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: proyecto2026
  labels:
    app: backend
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: 919820529775.dkr.ecr.us-east-1.amazonaws.com/proyecto/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 20
          startupProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 36
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
      terminationGracePeriodSeconds: 10
