apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: proyecto2026
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://api.agendaonline.cloud-ip.cc"
  BROADCAST_CONNECTION: "reverb"
  BROADCAST_DRIVER: "reverb"
  QUEUE_CONNECTION: "redis"
  CACHE_STORE: "redis"
  SESSION_DRIVER: "database"
  MAIL_MAILER: "smtp"
  MAIL_FROM_ADDRESS: "yoelleyes2013@gmail.com"
  MAIL_FROM_NAME: "AgendaOnline"
  SANCTUM_STATEFUL_DOMAINS: "app.agendaonline.cloud-ip.cc"
  FRONTEND_URL: "https://app.agendaonline.cloud-ip.cc"
  DB_CONNECTION: "pgsql"
  DB_PORT: "5432"
  REDIS_PORT: "6379"
